{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-developer
rules:
  - apiGroups:
      - pipeline.k-pipe.cloud
    resources:
      - pipelineschedules
      - pipelinedefinitions
      - pipelineruns
      - pipelinejobs
      - pipelineproblems
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
      - batch
    resources:
      - pods
      - jobs
      - cronjobs
      - persistentvolumeclaims
      - serviceaccounts
      - configmaps
    verbs:
      - get
      - list
      - watch
{{- end }}